# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "first-app-extension"
client_id = "91db64c231006148f307fdea08763893"
application_url = "https://problem-positions-floral-eight.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://problem-positions-floral-eight.trycloudflare.com/auth/callback",
  "https://problem-positions-floral-eight.trycloudflare.com/auth/shopify/callback",
  "https://problem-positions-floral-eight.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "coursecontactform.myshopify.com"
